Numpy library in Python:


*  Numpy (Numerical python) is the fundamental open-source library for scientific and numerical computing in python.
*  It provides support for large , high performing multi-dimensional arrays and matrices, along with a massive collection of high - level mathematical functions to operate on them.



How to install numpy library:
we install numpy using pip command

pip install numpy

In [1]:
a=list(range(20))
%timeit [i**2 for i in a]

1.21 µs ± 355 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [2]:
a=list(range(20000000))
%timeit [i**2 for i in a]

1.86 s ± 327 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
import numpy as np  #np is the instance of numpy library
b=np.array(range(20000000))
%timeit b**2

53.4 ms ± 858 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
a=list(range(20))
type(a)

list

In [5]:
a=list(range(20000000))
type(b)

numpy.ndarray

In [6]:
b=np.array(range(20000000))
type(b)
b

array([       0,        1,        2, ..., 19999997, 19999998, 19999999])

In [7]:
c1=np.arange(1,10)
print(c1)

[1 2 3 4 5 6 7 8 9]


In [8]:
c3=np.arange(1,10,0.5)
print(c3)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [9]:
b.ndim

1

In [10]:
len(b)

20000000

In [11]:
b.shape

(20000000,)

In [12]:
a=np.arange(1,10)
print(a)
print(a[-2])

[1 2 3 4 5 6 7 8 9]
8


Slicing on numpy array:

In [13]:
a[2:5]

array([3, 4, 5])

In [14]:
a[3:]

array([4, 5, 6, 7, 8, 9])

In [15]:
a[:2]

array([1, 2])

In [16]:
a[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[::2]

array([1, 3, 5, 7, 9])

In [25]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0:2,:])

[[10 20 30]
 [40 50 60]]


In [26]:
print(arr[:,0:2])

[[10 20]
 [40 50]
 [70 80]]


In [27]:
print(arr[2:,:])

[[70 80 90]]


In [49]:
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [50]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
a[:,1:2]

array([[2],
       [5],
       [8]])

Multi indexing:

In [20]:
a=[[10,20,30],[40,50,60],[70,80,90]]   #multi indexing at 2D list
a[0][1]

20

In [21]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])   #multi index
print(arr[0,1])
print(arr[1,2])
print(arr[2,0])

20
60
70


In [22]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])   # to access a entire row
print(arr[1])

[40 50 60]


In [23]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])  # to access a entire column
print(arr[:,1])

[20 50 80]


In [24]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])  # negative indexing
print(arr[-1,-1])

90


basic codes & functions of numpy



In [28]:
a=np.array([6,9,3,5,7,2,8,7])
a<6

array([False, False,  True,  True, False,  True, False, False])

In [29]:
a[a<6]

array([3, 5, 2])

In [30]:
a[a%2==0]

array([6, 2, 8])

In [31]:
a=np.array([-6,9,-3,0,5,7,-2,8,1])
print(a[a>0])

[9 5 7 8 1]


In [32]:
a=np.array(range(16))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
a.shape

(16,)

In [34]:
b=a.reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
a=np.array(range(16))


In [39]:
b.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
b.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.shape

(3, 4)

In [44]:
b=a.T  #transpose
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [45]:
b.ndim

2

In [46]:
b.shape

(4, 3)

In [47]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
print(a)
print(a[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [52]:
import numpy as np
a=np.array(range(25)).reshape(5,5)
print(a)
print(f"The element of that index :",a[[0,2,4,3],[1,3,0,4]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The element of that index : [ 1 13 20 19]


In [53]:
mask=(a%2==0)
a[mask]=-1
print(a)

[[-1  1 -1  3 -1]
 [ 5 -1  7 -1  9]
 [-1 11 -1 13 -1]
 [15 -1 17 -1 19]
 [-1 21 -1 23 -1]]


In [54]:
#Aggregate functions

a=np.array([10,20,35,40,55])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

160
32.0
10
55


In [55]:
a=np.array([10,20,35,4,55])
np.all(a<50)

np.False_

In [56]:
np.any(a<30)

np.True_

In [58]:
a=np.array([10,20,35,40,55])
b=np.where(a%2!=0 , -10,10)  #for checking condition
b

array([ 10,  10, -10,  10, -10])

In [60]:
#Sorting

a=np.array([100,210,50,140,155])
b=np.sort(a)
b

array([ 50, 100, 140, 155, 210])

In [61]:
#Sorting

a=np.array([100,210,50,140,155])
b=np.sort(a)
a

array([100, 210,  50, 140, 155])

In [64]:
a=np.array([100,210,50,140,155])
a.sort()
b=a.argsort()
b

array([0, 1, 2, 3, 4])

In [68]:
print(np.arange(5)) #arange function
print(np.ones(5))   # 1's print in the output
a=np.zeros(5)  # 0's print in the output
print(a)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [70]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(2,14).reshape(3,4)
print(a,"\n\n",b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [71]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(2,14).reshape(4,3)
print(a,"\n\n",b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [72]:
# Matrix multiplication
c=np.dot(a,b)
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [73]:
# another method for matrix multiplication
c=a@b
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [75]:
#This also one method of matrix multiplication
c=np.matmul(a,b)
c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [76]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [77]:
a.ndim

1

In [78]:
a.shape

(5,)

In [79]:
b=np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [80]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [81]:
c=np.dot(a,b)
c

np.int64(40)